### ISSUE TITLE
A way to use handle instead of email

### ISSUE THREAD

**Issue by nadavshatz** [HectorMalot/heap#1]
If you want to identify a user using the handle (like some sort of anonymous user) you can't do it at the moment.

I can create the option as a configuration value for the default used parameter, email/handle and send a pull request.

Let me know what you think.

Cheers for this Gem btw! I was just about to create one myself.

**Comment by HectorMalot** [comment]
That is a great idea! Happy to approve the pull request once you submit it. 
Cheers,
Dennis

**Comment by nadavshatz** [comment]
Done, you can see it at https://github.com/HectorMalot/heap/pull/2
Checkout my comments regarding the tests.

**Comment by HectorMalot** [comment]
Thx! I'll go over it in a few days, currently stuck w/o computer :)

**Comment by HectorMalot** [comment]
Closed with #2 , Thanks Nadav!

**Comment by nadavshatz** [comment]
Cheers!
