### ISSUE TITLE
Wrap window.heap.setEventProperties

### ISSUE THREAD

**Issue by jstrater** [HectorMalot/heap#3]
It's certainly possible to call `window.heap.setEventProperties` directly, but it would be nice to have a wrapper for it. `window.heap.identify` already has `heap_identify`.

I'm happy to submit a pull request for this if you're interested.

**Comment by HectorMalot** [comment]
Hi Josh,
Thanks for the input! Happy to accept your pull request if you want to wrap setEventProperties.
Cheers,
Dennis
